$(document).ready(function(){
    $(".pop-info__trigger")
        .mouseenter(function(){
            $(this).addClass("on");
            $(this).next(".pop-info__box").fadeIn(500);
        })
        .mouseleave(function(){
            $(this).removeClass("on");
            $(this).next(".pop-info__box").fadeOut(500);
        })
})
